//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ANMEntities : DbContext
    {
        public ANMEntities()
            : base("name=ANMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<BlockMast> BlockMasts { get; set; }
        public virtual DbSet<DistMast> DistMasts { get; set; }
        public virtual DbSet<QuestionMast> QuestionMasts { get; set; }
        public virtual DbSet<tbl_ImmunizationS1> tbl_ImmunizationS1 { get; set; }
    }
}
