//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionMast
    {
        public int Id { get; set; }
        public string QuesType { get; set; }
        public string QuesName { get; set; }
        public string QuesNo { get; set; }
        public string QuesText { get; set; }
        public string QuesAnswer { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
