//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ImmunizationS1
    {
        public int Id { get; set; }
        public string SubDate { get; set; }
        public string Sub_id { get; set; }
        public string MobileNo { get; set; }
        public string Q1_A { get; set; }
        public string Q2_A { get; set; }
        public string Q3_A { get; set; }
        public string Q4_A { get; set; }
        public string Q5_A { get; set; }
        public string Q6_A { get; set; }
        public string Q7_A { get; set; }
        public string Q8_A { get; set; }
        public string Q9_A { get; set; }
        public string G4_Q1 { get; set; }
        public string G5_Q2 { get; set; }
        public string G6_Q3 { get; set; }
        public string G7_Q4 { get; set; }
        public string G8_Q5 { get; set; }
        public string G9_Q6 { get; set; }
        public string Marks { get; set; }
        public string Q10_A { get; set; }
        public string Q11_A { get; set; }
        public string Q12_A { get; set; }
        public string C_tags { get; set; }
        public string C_uuid { get; set; }
        public string today { get; set; }
        public string G10_Q7 { get; set; }
        public string G11_Q8 { get; set; }
        public string G12_Q9 { get; set; }
        public string G2_ANM { get; set; }
        public string C_notes { get; set; }
        public string EndTime { get; set; }
        public string G13_Q10 { get; set; }
        public string G14_Q11 { get; set; }
        public string G15_Q12 { get; set; }
        public string C_edited { get; set; }
        public string C_status { get; set; }
        public string G2_BLOCK { get; set; }
        public string C_version { get; set; }
        public string C_duration { get; set; }
        public string C_xform_id { get; set; }
        public string timeStart { get; set; }
        public string G2_DISTRICT { get; set; }
        public string C_attachments { get; set; }
        public string C_geolocation { get; set; }
        public string C_media_count { get; set; }
        public string C_total_media { get; set; }
        public string formhub_uuid { get; set; }
        public string C_submitted_by { get; set; }
        public string C_date_modified { get; set; }
        public string meta_instanceID { get; set; }
        public string C_submission_time { get; set; }
        public string C_xform_id_string { get; set; }
        public string C_bamboo_dataset_id { get; set; }
        public string C_media_all_received { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    }
}
